# * POST to create a new admin

POST http://localhost:9000/api/admin/register
content-type: application/json

{
    "first_name": "Admin",
    "last_name": "Test",
    "email": "q@q.com",
    "password": "qwe789",
    "password_confirm": "qwe789"
}